### PR TITLE
version 1.3.0

### PR DESCRIPTION
**Pull request by gazugafan**
Hi Jas! You may have noticed my post on SmashBoards a couple days ago about some updates I had made to your Challonge Match Display program. I polished up my work, and here it is! If you want to merge it into your master branch and make a new release, that's awesome. If not, I understand and that's totally cool, too. Cheers!

Added scoreboard features.
Added option to save Challonge authentication.
Added ability to manage station list without CSV file.
UI improvements (easier score updating, double-clicking tournament).
Added Settings and About dialogs.

### CODE REVIEW

**Comment by JLaferri** [comment]
Hey Ken. Thanks for contributing! I did read your post on smashboards and will likely merge in your changes.

I just tried running it quickly and encountered a crash. I don't really have time to look into it now but I'll look at it later.

**Comment by gazugafan** [comment]
Ah, I see the problem. Was only cropping up on the first load (when you don't have any user settings created yet). Fixed!

**Comment by JLaferri** [comment]
Alright I merged it in and put a release out. When people open up their old 1.2.2 version they should get a notification that a new version was released. I haven't really explored the new features too in-depth but one thing I'm not too sure about is displaying the stream key so openly in the settings screen. I know it's not a big deal but one of the reasons I didn't have the ability to save it in the past was for security reasons. At the very least I think it should be hidden from the settings screen.

**Comment by gazugafan** [comment]
I hear you on the API key. It's also displayed on the first screen still. And even though that screen advances automatically when it's saved, you can still go back to it. I think the best solution would be to encrypt the API key using a PIN or password. Maybe a simpler solution would be to just show the user a big, scary, red warning when they check the box to save their API key in the settings dialog.

**Comment by JLaferri** [comment]
Actually when you go back to the first screen the program clears out the API key field.

In any case I think for now it'd be good enough to just hide it from the settings screen.

**Comment by gazugafan** [comment]
I think it stays there if you go back immediately before selecting a tournament.

**Comment by gazugafan** [comment]
I'll hide it on the settings screen soon, though.

**Pull request merged**
